"""
mobilenet_ood.py

Production Component 4 feature-space suitability/OOD gate - generic
ImageNet-pretrained MobileNetV2 centroid-distance check.

NOT a diagnostic system, NOT a "lung CT detector". This is a
distribution-shift/suitability check: does the uploaded image's
MobileNetV2 feature representation look reasonably close to the
Component 4 training distribution? A rejection means exactly:

    "This input is unsuitable for this component."

It must NEVER be interpreted as "Normal", "No cancer", or any
clinical claim - identical framing rule to lung_ct_validation.py's
check_lung_ct_suitability(), which this module runs ALONGSIDE, not
in place of. Both checks run; either can reject.

CALIBRATION - NOT performed by this module, and NOT recalibrated here.
Loads the existing, already-verified artifacts unchanged:
    centroid:  ood_calibration_mobilenet/mobilenet_lung_centroid.npy
    threshold: ood_calibration_mobilenet/mobilenet_ood_threshold_95.txt
Both were generated by the experimental
Files/calibrate_generic_mobilenet_ood.py script, and were empirically
re-verified against this exact production environment (Keras 3.14.0)
immediately before this module was written - a real run against all
481 held-out test images reproduced the original calibration's
category-level results exactly (e.g. abdominal_ct 25.00% rejection,
chest_xray 100.00% rejection, valid CT 99.11% acceptance, matching to
two decimal places). See project history for that verification run.
This module does not re-verify that on every startup - it trusts the
already-confirmed artifacts, exactly as instructed.

PREPROCESSING - reused byte-for-byte identical to the mobilenet_preprocess()
function in Files/calibrate_generic_mobilenet_ood.py and
Files/test_generic_mobilenet_ood.py, not reimplemented differently:
  - decode/resize match Component 4's existing convention
    (cv2.imdecode IMREAD_COLOR, 224x224, INTER_NEAREST)
  - explicit BGR->RGB conversion (MobileNetV2's pretrained weights
    expect RGB; cv2 decodes BGR - silently wrong without this, no
    error would be raised)
  - tf.keras.applications.mobilenet_v2.preprocess_input, mode="tf"
    (x/127.5 - 1.0) - NOT /255, verified against the installed Keras
    source during the original experiment, not assumed
If this function is ever edited, it must be edited identically in the
experimental scripts above, or the centroid/threshold will silently no
longer match what production actually computes.

Does NOT modify model.py, inference.py, gradcam.py, or
check_lung_ct_suitability() - this is an ADDITIONAL, separate gate.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field

import cv2
import numpy as np
import tensorflow as tf

IMG_SIZE = (224, 224)
RESIZE_INTERPOLATION = cv2.INTER_NEAREST
EXPECTED_FEATURE_DIM = 1280

CENTROID_PATH = os.path.join(
    os.path.dirname(__file__), "ood_calibration_mobilenet", "mobilenet_lung_centroid.npy"
)
THRESHOLD_PATH = os.path.join(
    os.path.dirname(__file__), "ood_calibration_mobilenet", "mobilenet_ood_threshold_95.txt"
)

_feature_model = None
_centroid = None
_threshold = None


def _get_feature_model():
    """Singleton, matching the existing project's module-level
    singleton pattern for loaded models (see model.py's get_model(),
    dicom_model.py's get_dicom_model()). Weights are ImageNet-pretrained
    and frozen - never fine-tuned, never trained here.
    """
    global _feature_model
    if _feature_model is None:
        backbone = tf.keras.applications.MobileNetV2(
            include_top=False, weights="imagenet", input_shape=(*IMG_SIZE, 3)
        )
        backbone.trainable = False
        x = tf.keras.layers.GlobalAveragePooling2D()(backbone.output)
        _feature_model = tf.keras.Model(inputs=backbone.input, outputs=x)
        print("✅ MobileNetV2 OOD feature extractor loaded")
    return _feature_model


def _get_centroid_and_threshold():
    """Loads the EXISTING, already-calibrated artifacts. Never
    recomputes them. Fails loudly and specifically if either file is
    missing or malformed, rather than silently proceeding with a
    default.
    """
    global _centroid, _threshold
    if _centroid is None:
        if not os.path.isfile(CENTROID_PATH):
            raise FileNotFoundError(
                f"MobileNet OOD centroid not found: {CENTROID_PATH}. "
                f"This file must exist before the application starts - "
                f"it is not generated at runtime."
            )
        loaded = np.load(CENTROID_PATH)
        if loaded.shape != (EXPECTED_FEATURE_DIM,):
            raise ValueError(
                f"MobileNet OOD centroid has unexpected shape {loaded.shape}, "
                f"expected ({EXPECTED_FEATURE_DIM},)."
            )
        _centroid = loaded
    if _threshold is None:
        if not os.path.isfile(THRESHOLD_PATH):
            raise FileNotFoundError(
                f"MobileNet OOD threshold not found: {THRESHOLD_PATH}."
            )
        _threshold = float(open(THRESHOLD_PATH).read().strip())
        print(f"✅ MobileNet OOD centroid/threshold loaded "
              f"(threshold={_threshold})")
    return _centroid, _threshold


def mobilenet_preprocess(image_bytes: bytes) -> np.ndarray:
    """See module docstring - identical to the experimental scripts'
    function of the same name. Do not edit without editing those too.
    """
    nparr = np.frombuffer(image_bytes, np.uint8)
    img_bgr = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    if img_bgr is None:
        raise ValueError("Image could not be decoded.")
    img_bgr = cv2.resize(img_bgr, IMG_SIZE, interpolation=RESIZE_INTERPOLATION)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    img_rgb = img_rgb.astype(np.float32)
    preprocessed = tf.keras.applications.mobilenet_v2.preprocess_input(img_rgb)
    return np.expand_dims(preprocessed, axis=0)


@dataclass
class MobilenetOodResult:
    """Deliberately mirrors lung_ct_validation.py's ValidationResult
    shape and user_message wording, so callers in comp4_service.py
    stay structurally consistent with the existing Level 2 check
    rather than introducing a second, differently-shaped result type.
    """
    is_valid: bool
    distance: float
    threshold: float
    reasons: list[str] = field(default_factory=list)

    @property
    def user_message(self) -> str:
        if self.is_valid:
            return ""
        return (
            "Unsupported image. This component accepts lung CT images only. "
            "Input is unsuitable for this component."
        )


def check_mobilenet_ood(image_bytes: bytes) -> MobilenetOodResult:
    """Feature-space suitability check - NOT a diagnostic classifier.
    See module docstring for the full framing.
    """
    feature_model = _get_feature_model()
    centroid, threshold = _get_centroid_and_threshold()

    preprocessed = mobilenet_preprocess(image_bytes)
    feature = feature_model(preprocessed, training=False).numpy()[0]

    distance = float(np.linalg.norm(feature - centroid))
    is_valid = distance <= threshold

    reasons = []
    if not is_valid:
        reasons.append(
            f"Image feature representation is too far from the Component 4 "
            f"training distribution (distance={distance:.4f}, "
            f"threshold={threshold:.4f})."
        )

    return MobilenetOodResult(
        is_valid=is_valid, distance=distance, threshold=threshold, reasons=reasons
    )
